name: iot_controller
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  grpc: ^3.2.4
  protobuf: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  image_path_android: "assets/images/icons/android/icon.png"
  image_path_ios: "assets/images/icons/ios/icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/icons/web/icon.png"
    windows:
      generate: true
      image_path: "assets/images/icons/web/icon.png"
      icon_size: 256
    macos:
      generate: true
      image_path: "assets/images/icons/web/icon.png"