name: iot_controller
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  grpc: ^4.0.0
  protobuf: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.5
  animated_custom_dropdown: ^3.1.1
  go_router: ^14.2.1
  geolocator: ^13.0.1
  flutter_staggered_grid_view: ^0.7.0
  interactive_slider: ^0.2.2
  string_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Bold.ttf
        - asset: fonts/TitilliumWeb-Black.ttf
#          weight: 900
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/models/
    - assets/models/Minidisc/files/minidisc.obj

flutter_launcher_icons:
  image_path_android: "assets/icons/android/icon.png"
  image_path_ios: "assets/icons/ios/icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/web/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/web/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/web/icon.png"
